"""unique-values

Revision ID: 21cd3c904e24
Revises: 20b78d3121c7
Create Date: 2024-05-15 20:42:35.202229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cd3c904e24'
down_revision: Union[str, None] = '20b78d3121c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'discipline', ['name', 'professor'])
    op.add_column('schedule', sa.Column('day_code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'schedule', ['discipline_id', 'day_code', 'time'])
    op.create_foreign_key(None, 'schedule', 'dictionary_schedule_day', ['day_code'], ['code'])
    op.drop_column('schedule', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='unique')
    op.drop_column('schedule', 'day_code')
    op.drop_constraint(None, 'discipline', type_='unique')
    # ### end Alembic commands ###
