# Generated by Django 5.0.6 on 2024-05-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryScheduleDay',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleapp.dictionaryscheduleday')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleapp.discipline')),
            ],
            options={
                'unique_together': {('discipline', 'day', 'time')},
            },
        ),
    ]
