# Generated by Django 5.0.6 on 2024-05-24 09:05

from django.db import migrations


def add_week_days(apps, schema_editor):
    DictionaryScheduleDay = apps.get_model('scheduleapp', 'DictionaryScheduleDay')
    # Додайте дані для всіх днів тижня
    week_days_data = [
        {'code': "Monday", 'label': "Понеділок"},
        {'code': "Tuesday", 'label': "Вівторок"},
        {'code': "Wednesday", 'label': "Середа"},
        {'code': "Thursday", 'label': "Четвер"},
        {'code': "Friday", 'label': "П'ятниця"},
        {'code': "Saturday", 'label': "Субота"},
        {'code': "Sunday", 'label': "Неділя"}
    ]
    for data in week_days_data:
        DictionaryScheduleDay.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_week_days),
    ]
